# Generated by Django 5.2.3 on 2025-06-19 10:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier for the URL. Will be auto-generated from the title.', max_length=200, unique=True)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Optional image for the news article.', max_length=255, null=True, verbose_name='News Image')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
