# Generated by Django 5.2.8 on 2026-04-13 11:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the gallery image.', max_length=255)),
                ('image', cloudinary.models.CloudinaryField(help_text='Image for the gallery.', max_length=255, verbose_name='Gallery Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
