# Generated by Django 5.2.3 on 2025-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField()),
                ('opponent', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('home_game', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['game_date'],
            },
        ),
    ]
