# Generated by Django 5.2.8 on 2026-01-23 02:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(blank=True, null=True)),
                ('game_time', models.TimeField(blank=True, default=datetime.time(12, 0), null=True)),
                ('opponent', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('game_type', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], default='HOME', max_length=4)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.league')),
            ],
            options={
                'ordering': ['game_date', 'game_time'],
            },
        ),
    ]
