# Generated by Django 5.2.3 on 2025-06-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Schedule',
        ),
    ]
