# Generated by Django 5.2.3 on 2025-06-23 07:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_game_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['game_date', 'game_time']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='home_game',
        ),
        migrations.AddField(
            model_name='schedule',
            name='game_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='game_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], default='HOME', max_length=4),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='game_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.league'),
        ),
    ]
