# Generated by Django 5.2.3 on 2025-06-30 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_league_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='game_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
    ]
