# Generated by Django 5.2.8 on 2026-01-23 02:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jersey_number', models.IntegerField(unique=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='Height in ft', max_digits=5, max_length=10, null=True)),
                ('weight', models.IntegerField(blank=True, help_text='Weight in kilograms', null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload player image', max_length=255, null=True, verbose_name='image')),
                ('position', models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Players',
                'ordering': ['jersey_number'],
            },
        ),
    ]
