# Generated by Django 5.2.3 on 2025-06-19 10:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jersey_number', models.IntegerField(unique=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=1, max_length=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=1, max_length=10, null=True)),
                ('image', cloudinary.models.CloudinaryField(help_text='Player Image.', max_length=255, verbose_name='News Image')),
                ('position', models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Players',
                'ordering': ['jersey_number'],
            },
        ),
    ]
