# Generated by Django 5.2.3 on 2025-06-19 11:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in ft', max_digits=5, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Player Image.', max_length=255, null=True, verbose_name='News Image'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kilograms', max_digits=5, max_length=10, null=True),
        ),
    ]
