# Generated by Django 5.2.3 on 2025-06-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_alter_player_height_alter_player_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload player image', null=True, upload_to='roster_images/'),
        ),
    ]
