# Generated by Django 5.2.3 on 2025-06-20 10:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload player image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
